### ISSUE TITLE
Can you provide documentation?

### ISSUE THREAD

**Issue by zhangfisher** [pexip/jostedal#1]
Can you provide documentation?
How to build a TURN server?
Can you provide an example?

**Comment by sporsh** [comment]
A simple [example script](../blob/master/scripts/jostedal) is provided to start a server:

```
jostedal INTERFACE [PORT [CONFIG-FILE]]
```

Configuration is read in from a JSON file (by default `jostedal.config` see example in [example.config](../blob/master/example.config)).

``` json
{
    "software": "Jostedal",
    "realm": "pexip.com",

    "users": {
        "passuser": {
            "password": "password"
        },
        "keyuser": {
            "key": "1b5c8156a9eee41c062037663f54cbac"
        }
    }
}
```

The values of the `software` and `realm` attributes can be configured here.

Long term credentials can also be specified - using either plain text passwords or HMAC-SHA-1 keys.  
To generate HMAC-SHA-1 keys, you can use the [hmac](../blob/master/scripts/hmac) script.

```
hmac USERNAME REALM [PASSWORD]
```
