### ISSUE TITLE
Use for production

### ISSUE THREAD

**Issue by mrtnetwork** [pexip/jostedal#4]
Hi,
I created a messenger for my program, but now it needs a turn and stun server for the webRTC system, can I use this source for production?
Thanks

**Comment by jmb202** [comment]
This really isn't a production-quality implementation as it is intended to be a test tool -- many STUN/TURN features are missing. The authentication implementation is designed to make it easy to write test cases, but is probably insufficient for the real world.

You'd do far better to use something like [coturn](https://github.com/coturn/coturn), which is a far more complete implementation of the STUN/TURN standards and has plenty of real-world deployments.
